"""PurpleForge bridge — export findings to defensive tooling."""

from __future__ import annotations

from typing import Any


def export_sigma_rules(findings: list[dict[str, Any]]) -> list[dict[str, str]]:
    """Generate Sigma rules from validated findings."""
    rules = []
    seen = set()

    templates = {
        "cmdi": {
            "title": "Command Injection Detected",
            "detection": "EventID: 4688 AND CommandLine|contains: ('cmd.exe','bash.exe','sh.exe')",
        },
        "ssrf": {
            "title": "SSRF Attempt",
            "detection": "NetworkConnect AND DestinationIp|startswith: ('10.','192.168.','127.')",
        },
        "secret": {
            "title": "Credential Access",
            "detection": "EventID: 4663 AND ObjectName|contains: ('.env','config.json','secrets')",
        },
        "sqli": {
            "title": "SQL Injection Attempt",
            "detection": "ApplicationLog AND Message|contains: ('SQL','syntax','error')",
        },
        "pathtraversal": {
            "title": "Path Traversal Attempt",
            "detection": "WebLog AND URL|contains: ('../','..%2f','..\\')",
        },
    }

    for f in findings:
        cat = f.get("category", "unknown")
        if cat in seen or cat not in templates:
            continue
        seen.add(cat)

        tmpl = templates[cat]
        yaml = f"""title: {tmpl['title']}
id: {hash(f['title']) % 10000000}
status: experimental
description: Auto-generated from GrooveStrike finding
logsource:
  product: windows
detection:
  condition: selection
  selection:
    {tmpl['detection']}
falsepositives:
  - Legitimate application behavior
level: {'high' if f.get('severity','') in ('critical','high') else 'medium'}
tags:
  - attack.execution
"""
        rules.append({"filename": f"groovestrike_{cat}.yml", "content": yaml})

    return rules


def export_atomic_tests(findings: list[dict[str, Any]]) -> list[dict[str, str]]:
    """Generate atomic test scripts from validated findings."""
    tests = []
    seen = set()

    for f in findings:
        cat = f.get("category", "unknown")
        if cat in seen:
            continue
        seen.add(cat)

        content = f"""# Atomic Test: {cat.upper()}
# Generated by GrooveStrike from finding: {f.get('title', 'Unknown')}
# SAFE — benign commands only

Write-Host "[+] Testing {cat} on target..." -ForegroundColor Cyan
# Add target-specific test commands here
# Finding: {f.get('description', 'No description')}
Write-Host "[+] Test complete." -ForegroundColor Green
"""
        tests.append({"filename": f"groovestrike_{cat}.ps1", "content": content})

    return tests


def export_to_groovehub_format(findings: list[dict[str, Any]]) -> dict[str, Any]:
    """Export findings in GrooveHub-compatible format."""
    return {
        "source": "groovestrike",
        "version": "0.1.0",
        "findings_count": len(findings),
        "findings": findings,
        "sigma_rules": export_sigma_rules(findings),
        "atomic_tests": export_atomic_tests(findings),
    }
